+incdir+$TB_HOME

//APB VIP
+incdir+$APB_VIP/src/hvl_top/test/sequences/master_sequences/
+incdir+$APB_VIP/src/hvl_top/master/
+incdir+$APB_VIP/src/hvl_top/env/virtual_sequencer/
+incdir+$APB_VIP/src/hvl_top/test/virtual_sequences/
+incdir+$APB_VIP/src/hvl_top/env
+incdir+$APB_VIP/src/hvl_top/slave
+incdir+$APB_VIP/src/hvl_top/test/sequences/slave_sequences/
+incdir+$APB_VIP/src/hvl_top/test
$APB_VIP/src/globals/apb_global_pkg.sv
$APB_VIP/src/hvl_top/master/apb_master_pkg.sv
$APB_VIP/src/hvl_top/slave/apb_slave_pkg.sv
$APB_VIP/src/hvl_top/test/sequences/master_sequences/apb_master_seq_pkg.sv
$APB_VIP/src/hvl_top/test/sequences/slave_sequences/apb_slave_seq_pkg.sv
$APB_VIP/src/hvl_top/env/apb_env_pkg.sv
$APB_VIP/src/hvl_top/test/virtual_sequences/apb_virtual_seq_pkg.sv
$APB_VIP/src/hvl_top/test/apb_test_pkg.sv
$APB_VIP/src/hdl_top/apb_if/apb_if.sv
$APB_VIP/src/hdl_top/master_agent_bfm/apb_master_driver_bfm.sv
$APB_VIP/src/hdl_top/master_agent_bfm/apb_master_monitor_bfm.sv
$APB_VIP/src/hdl_top/master_agent_bfm/apb_master_agent_bfm.sv
$APB_VIP/src/hdl_top/slave_agent_bfm/apb_slave_driver_bfm.sv
$APB_VIP/src/hdl_top/slave_agent_bfm/apb_slave_monitor_bfm.sv
$APB_VIP/src/hdl_top/slave_agent_bfm/apb_slave_agent_bfm.sv
//$APB_VIP/src/hdl_top/hdl_top.sv
//$APB_VIP/src/hvl_top/hvl_top.sv 

//AHB VIP
+incdir+$AHB_VIP/src/globals/
+incdir+$AHB_VIP/src/hvlTop/masterAgent/masterSequences
+incdir+$AHB_VIP/src/hvlTop/masterAgent
+incdir+$AHB_VIP/src/hvlTop/slaveAgent
+incdir+$AHB_VIP/src/hvlTop/slaveAgent/slaveSequences/
+incdir+$AHB_VIP/src/hvlTop/environment/virtualSequencer
+incdir+$AHB_VIP/src/hvlTop/tb/virtualSequences/
+incdir+$AHB_VIP/src/hvlTop/environment
+incdir+$AHB_VIP/src/hvlTop/tb/test
+incdir+$AHB_VIP/src/hvlTop/
+incdir+$AHB_VIP/src/hdlTop/
$AHB_VIP/src/globals/AhbGlobalPackage.sv
$AHB_VIP/src/hvlTop/masterAgent/AhbMasterPackage.sv
$AHB_VIP/src/hvlTop/slaveAgent/AhbSlavePackage.sv
$AHB_VIP/src/hvlTop/masterAgent/masterSequences/AhbMasterSequencePackage.sv
$AHB_VIP/src/hvlTop/slaveAgent/slaveSequences/AhbSlaveSequencePackage.sv
$AHB_VIP/src/hvlTop/environment/AhbEnvironmentPackage.sv
$AHB_VIP/src/hvlTop/tb/virtualSequences/AhbVirtualSequencePackage.sv
$AHB_VIP/src/hvlTop/tb/test/AhbTestPackage.sv
$AHB_VIP/src/hdlTop/ahbInterface/AhbInterface.sv
$AHB_VIP/src/hdlTop/masterAgentBFM/AhbMasterDriverBFM.sv
$AHB_VIP/src/hdlTop/masterAgentBFM/AhbMasterMonitorBFM.sv
$AHB_VIP/src/hdlTop/masterAgentBFM/AhbMasterAgentBFM.sv
$AHB_VIP/src/hdlTop/masterAgentBFM/AhbMasterAssertion.sv
$AHB_VIP/src/hdlTop/slaveAgentBFM/AhbSlaveDriverBFM.sv
$AHB_VIP/src/hdlTop/slaveAgentBFM/AhbSlaveMonitorBFM.sv
$AHB_VIP/src/hdlTop/slaveAgentBFM/AhbSlaveAgentBFM.sv
$AHB_VIP/src/hdlTop/slaveAgentBFM/AhbSlaveAssertion.sv
$AHB_VIP/src/hdlTop/masterAgentBFM/AhbMasterCoverProperty.sv
$AHB_VIP/src/hdlTop/slaveAgentBFM/AhbSlaveCoverProperty.sv
//$AHB_VIP/src/hdlTop/HdlTop.sv
//$AHB_VIP/src/hvlTop/HvlTop.sv 

//AXI VIP
+incdir+$AXI_VIP/src/globals/
+incdir+$AXI_VIP/src/hvl_top/test/sequences/master_sequences/
+incdir+$AXI_VIP/src/hvl_top/master/
+incdir+$AXI_VIP/src/hdl_top/master_agent_bfm/ 
+incdir+$AXI_VIP/src/hvl_top/env/virtual_sequencer/
+incdir+$AXI_VIP/src/hvl_top/test/virtual_sequences/
+incdir+$AXI_VIP/src/hvl_top/env
+incdir+$AXI_VIP/src/hvl_top/slave
+incdir+$AXI_VIP/src/hvl_top/test/sequences/slave_sequences/
+incdir+$AXI_VIP/src/hvl_top/test
+incdir+$AXI_VIP/src/hdl_top/slave_agent_bfm
+incdir+$AXI_VIP/src/hdl_top/axi4_interface
$AXI_VIP/src/globals/axi4_globals_pkg.sv
$AXI_VIP/src/hvl_top/master/axi4_master_pkg.sv
$AXI_VIP/src/hvl_top/slave/axi4_slave_pkg.sv
$AXI_VIP/src/hvl_top/test/sequences/master_sequences/axi4_master_seq_pkg.sv
$AXI_VIP/src/hvl_top/test/sequences/slave_sequences/axi4_slave_seq_pkg.sv
$AXI_VIP/src/hvl_top/env/axi4_env_pkg.sv
$AXI_VIP/src/hvl_top/test/virtual_sequences/axi4_virtual_seq_pkg.sv
$AXI_VIP/src/hvl_top/test/axi4_test_pkg.sv
$AXI_VIP/src/hdl_top/axi4_interface/axi4_if.sv
$AXI_VIP/src/hdl_top/master_agent_bfm/axi4_master_driver_bfm.sv
$AXI_VIP/src/hdl_top/master_agent_bfm/axi4_master_monitor_bfm.sv
$AXI_VIP/src/hdl_top/master_agent_bfm/axi4_master_agent_bfm.sv
$AXI_VIP/src/hdl_top/slave_agent_bfm/axi4_slave_driver_bfm.sv
$AXI_VIP/src/hdl_top/slave_agent_bfm/axi4_slave_monitor_bfm.sv
$AXI_VIP/src/hdl_top/slave_agent_bfm/axi4_slave_agent_bfm.sv
//$AXI_VIP/src/hdl_top/hdl_top.sv
//$AXI_VIP/src/hvl_top/hvl_top.sv
$AXI_VIP/src/hdl_top/master_assertions.sv
$AXI_VIP/src/hdl_top/slave_assertions.sv

//JTAG VIP
+incdir+$JTAG_VIP/src/hvlTop/jtagControllerDeviceAgent/jtagControllerDeviceSequences/
+incdir+$JTAG_VIP/src/hvlTop/jtagControllerDeviceAgent/
+incdir+$JTAG_VIP/src/hvlTop/jtagEnv/virtualSequencer/
+incdir+$JTAG_VIP/src/hvlTop/tb/jtagVirtualSequences/
+incdir+$JTAG_VIP/src/hvlTop/jtagEnv
+incdir+$JTAG_VIP/src/hvlTop/jtagTargetDeviceAgent
+incdir+$JTAG_VIP/src/hvlTop/jtagTargetDeviceAgent/jtagTargetDeviceSequences/
+incdir+$JTAG_VIP/src/hvlTop/tb
+incdir+$JTAG_VIP/src/hvlTop/tb/test
$JTAG_VIP/src/globals/JtagGlobalPkg.sv
$JTAG_VIP/src/hvlTop/jtagControllerDeviceAgent/JtagControllerDevicePkg.sv
$JTAG_VIP/src/hvlTop/jtagTargetDeviceAgent/JtagTargetDevicePkg.sv
$JTAG_VIP/src/hvlTop/jtagControllerDeviceAgent/jtagControllerDeviceSequences/JtagControllerDeviceSequencePkg.sv
$JTAG_VIP/src/hvlTop/jtagTargetDeviceAgent/jtagTargetDeviceSequences/JtagTargetDeviceSequencePkg.sv
$JTAG_VIP/src/hvlTop/jtagEnv/JtagEnvPkg.sv
$JTAG_VIP/src/hvlTop/tb/jtagVirtualSequences/JtagVirtualSequencePkg.sv
$JTAG_VIP/src/hvlTop/tb/test/JtagBaseTestPkg.sv
$JTAG_VIP/src/hdlTop/jtagInterface/JtagInterface.sv
$JTAG_VIP/src/hdlTop/jtagControllerDeviceAgentBfm/JtagControllerDeviceDriverBfm.sv
$JTAG_VIP/src/hdlTop/jtagControllerDeviceAgentBfm/JtagControllerDeviceMonitorBfm.sv
$JTAG_VIP/src/hdlTop/jtagControllerDeviceAgentBfm/JtagControllerDeviceAgentBfm.sv
$JTAG_VIP/src/hdlTop/jtagTargetDeviceAgentBfm/JtagTargetDeviceDriverBfm.sv
$JTAG_VIP/src/hdlTop/jtagTargetDeviceAgentBfm/JtagTargetDeviceMonitorBfm.sv
$JTAG_VIP/src/hdlTop/jtagTargetDeviceAgentBfm/JtagTargetDeviceAgentBfm.sv
//$JTAG_VIP/src/hdlTop/JtagHdlTop.sv
//$JTAG_VIP/src/hvlTop/JtagHvlTop.sv
$JTAG_VIP/src/hdlTop/jtagControllerDeviceAgentBfm/JtagControllerDeviceAssertions.sv
$JTAG_VIP/src/hdlTop/jtagTargetDeviceAgentBfm/JtagTargetDeviceAssertions.sv

//Seq
+incdir+$TB_HOME/seq
$TB_HOME/seq/soc_seq_pkg.sv

//Test
+incdir+$TB_HOME/test
$TB_HOME/test/soc_test_pkg.sv

//TB TOP
+incdir+$TB_HOME/tb
$TB_HOME/tb/tb_macro.sv
$TB_HOME/tb/tb_top.sv
